test/base/Mocked.scala
test/base/SpecBase.scala
test/controllers/TrustNameControllerSpec.scala
test/controllers/TrustResidentOffshoreControllerSpec.scala
test/controllers/WhenTrustSetupControllerSpec.scala

- No longer making calls to Mongo in controller POSTs

Fix session repository mocking

---

app/assets/stylesheets/_conditionals.scss
app/views/GovukWrapper.scala.html
project/AppDependencies.scala

Upgrading org.reactivemongo.play2-reactivemongo-0.16.2-play26.
Skipping 0.16.1 as no artefact published.

TRUS-645 Upgrade reactive mongo to 0.16.2

---

app/views/AddATrusteeView.scala.html
app/views/components/data_list.scala.html
conf/messages.en
test/views/behaviours/TabularDataViewBehaviours.scala

- Add H2 for screen readers for AddATrustee

TRUS-593 Add H2 for screen readers

---

app/config/FrontendAppConfig.scala
app/controllers/CreateAgentServicesAccountController.scala
app/controllers/actions/IdentifierAction.scala
app/views/CreateAgentServicesAccountView.scala.html
conf/app.routes
conf/application.conf
conf/messages.en
test/controllers/CreateAgentServicesAccountControllerSpec.scala
test/controllers/actions/AuthActionSpec.scala
test/views/CreateAgentServicesAccountViewSpec.scala

[TRUS-383] - Agent logged in front-end microservice has HMRC-AS-AGENT enrolment

[TRUS-383] - Agent logged in front-end microservice has HMRC-AS-AGENT enrolment

---

app/controllers/CheckYourAnswersController.scala
app/controllers/TrustDetailsAnswerPageController.scala
app/controllers/TrusteesAnswerPageController.scala
app/navigation/Navigator.scala
app/pages/TrustDetailsAnswerPage.scala
app/utils/CheckYourAnswersHelper.scala
app/views/TrustDetailsAnswerPageView.scala.html
conf/app.routes
conf/messages.en
test/controllers/TrustDetailsAnswerPageControllerSpec.scala
test/controllers/TrusteesAnswerPageControllerSpec.scala
test/navigation/NavigatorSpec.scala
test/navigation/navigators/TrustDetailsRoutes.scala
test/views/TrustDetailsAnswerPageViewSpec.scala

- Add check your answers for trust details
- Navigator logic change to route to trustees after completing section
- Implement two of the change links to function as expected
- Parsing country codes in rendering FR becomes France

TRUS-337 Trust Details Check Answers with country parsing

---

app/navigation/Navigator.scala
app/pages/TrusteeLiveInTheUKPage.scala
conf/messages.en
test/navigation/navigators/TrusteeRoutes.scala

Wiring navigation together for TrusteeLiveInUK, TrusteeNino and TrusteeTelephoneNumber

Fix navigation between trutees page and content

---

app/forms/Validation.scala

[TRUS-588] - Correct Telephone RegEx

[TRUS-588] - Correct Telephone RegEx

---

app/assets/stylesheets/trustsfrontend-app.scss
app/controllers/TrusteesInfoController.scala
app/views/TrusteesInfoView.scala.html
conf/app.routes
conf/messages.en
migrations/applied_migrations/TrusteesInfo.sh
test/controllers/TrusteesInfoControllerSpec.scala
test/views/TrusteesInfoViewSpec.scala

[TRUS-482] - Interrupt page

---

app/assets/javascripts/trustsfrontend.js
app/assets/stylesheets/trustsfrontend-app.scss
app/views/TrustHaveAUTRView.scala.html
app/views/TrustRegisteredOnlineView.scala.html
app/views/TrusteesNameView.scala.html
app/views/WhatIsTheUTRView.scala.html
app/views/components/error_summary.scala.html
app/views/components/input_text.scala.html
app/views/components/input_yes_no.scala.html
conf/messages.en
test/views/ViewSpecBase.scala
test/views/behaviours/QuestionViewBehaviours.scala
test/views/behaviours/YesNoViewBehaviours.scala

[TRUS-906] - Accessibility - Jaws & VO - H1 repeated as part of hint text

[TRUS-906] - Accessibility - Jaws & VO - H1 repeated as part of hint text

---

app/views/WhatIsTheUTRView.scala.html
app/views/components/input_text.scala.html
conf/messages.en

Refactored  input_text helper to accept an alternative screen reader hint message

[TRUS-919] - Accessibility - VO - Reads SA316 as saaa316

---

app/assets/javascripts/trustsfrontend.js

Simplified javaScript back-link onClick funtion.

[TRUS-904] - Accessibility - Jaws - Back link does not work

---

app/assets/stylesheets/trustsfrontend-app.scss

[TRUS-820] - CBT - Country selection field too long when activated

---

app/assets/stylesheets/trustsfrontend-app.scss

TRUS-820 Fix for responsive country lookup

---

app/assets/javascripts/trustsfrontend.js

Fix JS issue with input of country without selection from country dropdown

[TRUS-930] - Accessibility - Country List

---

app/navigation/Navigator.scala
test/navigation/NavigatorSpec.scala
test/navigation/navigators/DeceasedSettlorRoutes.scala

- navigation for deceased settlor when answer no to everything.

Deceased settlor no route

---

app/controllers/SettlorsNameController.scala
app/forms/SettlorsNameFormProvider.scala
app/pages/SettlorsNamePage.scala
app/utils/CheckYourAnswersHelper.scala
app/views/SettlorsNameView.scala.html
test/controllers/SettlorsNameControllerSpec.scala
test/forms/SettlorsNameFormProviderSpec.scala
test/navigation/TaskListNavigatorSpec.scala
test/pages/SettlorsNamePageSpec.scala
test/pages/SetupAfterSettlorDiedPageSpec.scala
test/views/SettlorsNameViewSpec.scala

- updated model change for settlor name 
-updated view as per full name model.

Model changes

---

app/pages/DeceasedSettlor.scala
app/pages/SettlorDateOfDeathPage.scala
app/pages/SettlorDateOfDeathYesNoPage.scala
app/pages/SettlorNationalInsuranceNumberPage.scala
app/pages/SettlorsDateOfBirthPage.scala
app/pages/SettlorsInternationalAddressPage.scala
app/pages/SettlorsLastKnownAddressYesNoPage.scala
app/pages/SettlorsNINoYesNoPage.scala
app/pages/SettlorsNamePage.scala
app/pages/SettlorsUKAddressPage.scala
app/pages/SetupAfterSettlorDiedPage.scala
app/pages/WasSettlorsAddressUKYesNoPage.scala

Mongo indexing for deceased settlor

Mongo indexing for deceased settlor

---

app/views/SettlorsInternationalAddressView.scala.html
app/views/SettlorsUKAddressView.scala.html
conf/messages.en
test/controllers/SettlorsInternationalAddressControllerSpec.scala
test/controllers/SettlorsNameControllerSpec.scala
test/controllers/SettlorsUKAddressControllerSpec.scala
test/views/SettlorsInternationalAddressViewSpec.scala
test/views/SettlorsUKAddressViewSpec.scala
test/views/TrusteeUKAddressViewSpec.scala

Address view models

---

app/controllers/AssetMoneyValueController.scala
app/forms/AssetMoneyValueFormProvider.scala
app/forms/Validation.scala
app/forms/mappings/Formatters.scala
app/forms/mappings/Mappings.scala
conf/messages.en
test/controllers/AssetMoneyValueControllerSpec.scala
test/forms/AssetMoneyValueFormProviderSpec.scala
test/forms/behaviours/IntFieldBehaviours.scala
test/forms/mappings/MappingsSpec.scala
test/generators/Generators.scala

- check for £0 in value field
- error message for £0 value
- currency 1000 seperator

TRUS-813D1

---

app/views/components/select.scala.html
test/views/SettlorsInternationalAddressViewSpec.scala

view-spec-fix

---

app/controllers/TrusteesNinoController.scala
app/forms/SettlorNationalInsuranceNumberFormProvider.scala
app/forms/TrusteesNinoFormProvider.scala
app/forms/mappings/Formatters.scala
app/forms/mappings/Mappings.scala

Nino formatter

---

app/controllers/IndividualBeneficiaryDateOfBirthYesNoController.scala
app/navigation/Navigator.scala
app/pages/IndividualBeneficiaryDateOfBirthYesNoPage.scala
app/utils/CheckYourAnswersHelper.scala
app/views/IndividualBeneficiaryDateOfBirthYesNoView.scala.html
conf/app.routes
conf/messages.en
test/controllers/IndividualBeneficiaryDateOfBirthYesNoControllerSpec.scala
test/generators/PageGenerators.scala
test/generators/UserAnswersEntryGenerators.scala
test/generators/UserAnswersGenerator.scala
test/navigation/navigators/BeneficiaryRoutes.scala
test/pages/IndividualBeneficiaryDateOfBirthYesNoPageSpec.scala
test/views/IndividualBeneficiaryDateOfBirthYesNoViewSpec.scala

individual-ben-dob-yes-no

---

app/controllers/IndividualBeneficiaryDateOfBirthController.scala
app/forms/IndividualBeneficiaryDateOfBirthFormProvider.scala
app/navigation/Navigator.scala
app/pages/IndividualBeneficiaryDateOfBirthPage.scala
app/utils/CheckYourAnswersHelper.scala
app/views/IndividualBeneficiaryDateOfBirthView.scala.html
conf/app.routes
conf/messages.en
test/controllers/IndividualBeneficiaryDateOfBirthControllerSpec.scala
test/controllers/IndividualBeneficiaryDateOfBirthYesNoControllerSpec.scala
test/forms/IndividualBeneficiaryDateOfBirthFormProviderSpec.scala
test/generators/PageGenerators.scala
test/generators/UserAnswersEntryGenerators.scala
test/generators/UserAnswersGenerator.scala
test/navigation/navigators/BeneficiaryRoutes.scala
test/pages/IndividualBeneficiaryDateOfBirthPageSpec.scala
test/views/IndividualBeneficiaryDateOfBirthViewSpec.scala

individual-ben-dob

---

app/controllers/IndividualBeneficiaryAnswersController.scala
app/controllers/IndividualBeneficiaryVulnerableYesNoController.scala
app/navigation/Navigator.scala
app/pages/IndividualBeneficiaryVulnerableYesNoPage.scala
app/utils/CheckYourAnswersHelper.scala
app/views/IndividualBeneficiaryVulnerableYesNoView.scala.html
conf/app.routes
conf/messages.en
test/controllers/IndividualBeneficiaryAnswersControllerSpec.scala
test/controllers/IndividualBeneficiaryVulnerableYesNoControllerSpec.scala
test/generators/PageGenerators.scala
test/generators/UserAnswersEntryGenerators.scala
test/generators/UserAnswersGenerator.scala
test/navigation/navigators/BeneficiaryRoutes.scala
test/pages/IndividualBeneficiaryVulnerableYesNoPageSpec.scala
test/views/IndividualBeneficiaryVulnerableYesNoViewSpec.scala

Indexing, content, validation, check answers

individual-ben-vulnerable

---

app/views/IndividualBeneficiaryDateOfBirthYesNoView.scala.html
app/views/IndividualBeneficiaryNationalInsuranceNumberView.scala.html
app/views/IndividualBeneficiaryNationalInsuranceYesNoView.scala.html
app/views/IndividualBeneficiaryVulnerableYesNoView.scala.html
conf/messages.en

individual-ben-accessibility

---

app/pages/IndividualBeneficiaryDateOfBirthYesNoPage.scala
app/pages/IndividualBeneficiaryIncomeYesNoPage.scala
test/pages/IndividualBeneficiaryDateOfBirthYesNoPageSpec.scala
test/pages/IndividualBeneficiaryIncomeYesNoPageSpec.scala

- clean up for the date of birth yes no page
- clean up for income yes no page for the individual beneficiary.

clean up logic

---

app/controllers/AddABeneficiaryController.scala
app/models/AddABeneficiary.scala
app/models/entities/IndividualBeneficiary.scala
app/navigation/Navigator.scala
app/navigation/TaskListNavigator.scala
app/utils/AddABeneficiaryViewHelper.scala
app/utils/CheckYourAnswersHelper.scala
app/views/AddABeneficiaryView.scala.html
app/views/IndividualBeneficiaryIncomeYesNoView.scala.html
conf/app.routes
conf/messages.en
test/controllers/AddABeneficiaryControllerSpec.scala
test/forms/AgentTelephoneNumberFormProviderSpec.scala
test/navigation/TaskListNavigatorSpec.scala
test/navigation/navigators/BeneficiaryRoutes.scala
test/views/AddABeneficiaryViewSpec.scala
test/views/IndividualBeneficiaryIncomeYesNoViewSpec.scala

Add beneficiary

---

app/repositories/SessionRepository.scala

- replaced deprecated update method

change deprecated update method

---

app/navigation/TaskListNavigator.scala
app/views/AssetInterruptPageView.scala.html
conf/messages.en
test/navigation/TaskListNavigatorSpec.scala
test/views/AssetInterruptPageViewSpec.scala

[TRUS-973] - Add to Asset Interrupt Page

---

app/controllers/ClassBeneficiaryDescriptionController.scala
app/forms/ClassBeneficiaryDescriptionFormProvider.scala
app/forms/Validation.scala
app/models/entities/ClassOfBeneficiary.scala
app/pages/ClassBeneficiaryDescriptionPage.scala
app/pages/ClassOfBeneficiaries.scala
app/utils/CheckYourAnswersHelper.scala
app/views/ClassBeneficiaryDescriptionView.scala.html
conf/app.routes
conf/messages.en
migrations/applied_migrations/ClassBeneficiaryDescription.sh
test/controllers/ClassBeneficiaryDescriptionControllerSpec.scala
test/forms/ClassBeneficiaryDescriptionFormProviderSpec.scala
test/forms/IndividualBeneficiaryIncomeFormProviderSpec.scala
test/generators/PageGenerators.scala
test/generators/UserAnswersEntryGenerators.scala
test/generators/UserAnswersGenerator.scala
test/pages/ClassBeneficiaryDescriptionPageSpec.scala
test/views/ClassBeneficiaryDescriptionViewSpec.scala

- description page for class of beneficiary
- it is unidentified benficiary in des schema.

[TRUS-392] Class of beneficiary description page.

---

conf/messages.en

- agent check your answer page message update

TRUS-1049 agent check your answer

---

conf/messages.en

TRUS-1052: Error message update

---

app/controllers/TaskListController.scala
app/models/entities/Trustee.scala
app/pages/RegistrationProgress.scala
app/views/TaskListView.scala.html
conf/messages.en
test/controllers/AddATrusteeControllerSpec.scala
test/controllers/TaskListControllerSpec.scala
test/models/reads/TrusteeReadsSpec.scala
test/utils/AddATrusteeViewHelperSpec.scala
test/views/TaskListViewSpec.scala

Spec amends.
Logic for status tags.
Content amends.

[TRUS-1031] - Registration Progress - Summary text

---

app/controllers/TaskListController.scala
app/models/entities/Trustee.scala
app/pages/RegistrationProgress.scala
app/views/TaskListView.scala.html
conf/messages.en
test/controllers/AddATrusteeControllerSpec.scala
test/controllers/TaskListControllerSpec.scala
test/models/reads/TrusteeReadsSpec.scala
test/utils/AddATrusteeViewHelperSpec.scala
test/views/TaskListViewSpec.scala

Reverts hmrc/trusts-frontend#143

Revert "[TRUS-1031] - Registration Progress - Summary text"

---

app/mapping/NameMapper.scala
app/mapping/TrusteeMapper.scala
test/mapping/TrusteeMapperSpec.scala

Mapping trustee individual type to TrusteeType

[TUST-1192] Mapping trustee type

---

app/mapping/DeceasedSettlorMapper.scala
test/mapping/DeceasedSettlorMapperSpec.scala

Deceased Settlor Mapping

---

app/controllers/AssetMoneyValueController.scala
app/controllers/WhatKindOfAssetController.scala
app/models/entities/Asset.scala
app/models/entities/Assets.scala
app/models/entities/MoneyAsset.scala
app/navigation/Navigator.scala
app/navigation/TaskListNavigator.scala
app/pages/RegistrationProgress.scala
app/pages/WhatKindOfAssetPage.scala
app/pages/entitystatus/AssetStatus.scala
app/utils/AddAssetViewHelper.scala
app/viewmodels/Assets.scala
app/viewmodels/addAnother/AssetViewModel.scala
app/viewmodels/addAnother/DefaultAssetsViewModel.scala
app/viewmodels/addAnother/MoneyAssetViewModel.scala
conf/messages.en
test/controllers/AddAssetsControllerSpec.scala
test/models/reads/AssetReadsSpec.scala
test/navigation/TaskListNavigatorSpec.scala
test/pages/RegistrationProgressSpec.scala
test/viewmodels/AssetViewModelSpec.scala

Implementing ViewModel for assets subtypes. This is then used to render the InProgress/Completed tag on the task list for the assets section.

TaskList assets in-progress and complete tag

---

app/mapping/AddressMapper.scala
app/mapping/LeadTrusteeMapper.scala
app/mapping/SchemaModels.scala
app/mapping/TrusteeMapper.scala
app/models/entities/LeadTrusteeIndividual.scala
app/models/entities/Trustee.scala
app/models/entities/TrusteeIndividual.scala
test/mapping/LeadTrusteeMapperSpec.scala
test/mapping/TrusteeMapperSpec.scala
test/models/reads/TrusteeReadsSpec.scala

- mapping of lead trustee model to lead trustee type of api.

[TRUS-1196] Mapping of lead trustee 

---

app/mapping/ClassOfBeneficiariesMapper.scala
app/models/entities/ClassOfBeneficiaries.scala
app/models/entities/ClassOfBeneficiary.scala
app/models/entities/IndividualBeneficiaries.scala
app/models/entities/IndividualBeneficiary.scala
app/models/entities/LeadTrusteeIndividual.scala
app/viewmodels/addAnother/ClassOfBeneficiaryViewModel.scala
test/mapping/ClassOfBeneficiariesMapperSpec.scala

[TRUS-1195] - Class of beneficiary

[TRUS-1195] - Class of beneficiary

---

app/mapping/IndividualBeneficiaryMapper.scala
app/mapping/SchemaModels.scala
app/models/entities/IndividualBeneficiary.scala
test/mapping/IndividualBeneficiaryMapperSpec.scala

- mapping individual beneficiary to api Individual Beneficiary Type

[TRUS-1194] Mapper for Individual Beneficiary

---

app/mapping/DeclarationMapper.scala
test/mapping/DeclarationMapperSpec.scala

[TRUS-1199] - Declaration

---

app/controllers/TaskListController.scala
app/mapping/DeceasedSettlorMapper.scala
app/mapping/MatchingMapper.scala
app/mapping/RegistrationMapper.scala
app/mapping/SchemaModels.scala
app/services/SubmissionService.scala
test/base/SpecBase.scala
test/mapping/AgentMapperSpec.scala
test/mapping/MatchingMapperSpec.scala
test/mapping/RegistrationMapperSpec.scala
test/resources/logback-test.xml
test/utils/TestUserAnswers.scala

This completes mapping for matching and the overall registration object for submission to the backend.

TRUS-1198 Implement Registration mapper with matching

---

app/config/FrontendAppConfig.scala
app/controllers/ConfirmationController.scala
conf/application.conf
test/controllers/ConfirmationControllerSpec.scala

- showing actual trn number from database.

[TRUS-755] Showing saved TRN number.

---

app/controllers/ConfirmationController.scala
app/models/entities/LeadTrusteeIndividual.scala
app/models/entities/Trustee.scala
app/models/entities/TrusteeIndividual.scala
app/views/ConfirmationView.scala.html
app/views/components/link.scala.html
conf/messages.en
test/controllers/ConfirmationControllerSpec.scala
test/views/ConfirmationViewSpec.scala
test/views/ViewSpecBase.scala

Also renders a link if the AffinityGroup is an Agent.

TRUS-755 Confirmation page for new and existing trusts

---

conf/application.conf
test/filters/WhitelistFilterSpec.scala

TRUS-1058 - fix unit test

---

app/utils/AccessibilityHelper.scala
app/views/ConfirmationAnswerPageView.scala.html
app/views/ConfirmationView.scala.html
test/utils/AccessibilityHelperSpec.scala
test/views/ConfirmationAnswerPageViewSpec.scala
test/views/ConfirmationViewSpec.scala
test/views/behaviours/ViewBehaviours.scala

[TRUS-1226] - Accessibility - Jaws - Confirmation page - TRN read out as a whole number

[TRUS-1226] - Accessibility - Jaws - Confirmation page - TRN

---

app/auditing/RegistrationErrorAuditEvent.scala
app/auditing/TrustAuditing.scala
app/auditing/TrustRegistrationSubmissionAuditEvent.scala
app/config/FrontendAppConfig.scala
app/models/RegistrationTRNResponse.scala
app/services/AuditService.scala
app/services/SubmissionService.scala
conf/application.conf
test/base/Mocked.scala
test/services/FakeAuditService.scala
test/services/SubmissionServiceSpec.scala

Adding audit events following a discussion with the TXM team.

TRUS-1214 Adding TXM audit events

---

app/controllers/ConfirmationController.scala
app/controllers/DeclarationController.scala
app/controllers/TaskListController.scala
app/controllers/actions/DataRetrievalAction.scala
app/controllers/actions/DraftIdRetrievalAction.scala
app/controllers/actions/RequireDraftRegistrationActionRefiner.scala
app/models/RegistrationStatus.scala
app/models/UserAnswers.scala
app/pages/RegistrationProgress.scala
app/repositories/SessionRepository.scala
test/base/SpecBase.scala
test/controllers/ConfirmationControllerSpec.scala
test/controllers/DeclarationControllerSpec.scala
test/controllers/IndexControllerSpec.scala
test/controllers/actions/FakeDraftIdRetrievalActionProvider.scala
test/controllers/actions/RequireDraftRegistrationActionRefinerSpec.scala
test/pages/RegistrationProgressSpec.scala

- Checking size of list following a bug which was identified where all
the entities in the list were removed

TRUS-1503 Fix bug identified in task list status logic

---

app/mapping/TaxLiabilityMapper.scala
test/mapping/RegistrationMapperSpec.scala
test/mapping/TaxLiabilityMapperSpec.scala

Updated TaxLibailityMapper to return None as opposed to Some(YearsReturns(Some ...

TRUS-1193: Remove code that created years of tax consequence

---

app/controllers/AddABeneficiaryController.scala
conf/messages.en

Re-adding this following a conversation with Anita, this was reverted following a peer review I'm assuming as it does not align with the prototype.

Adding in content for singular beneficiary added

---

app/controllers/AddAssetsController.scala
app/controllers/RemoveAssetController.scala
app/controllers/RemoveClassOfBeneficiaryController.scala
app/controllers/RemoveIndexController.scala
app/controllers/RemoveIndividualBeneficiaryController.scala
app/controllers/money/RemoveMoneyAssetController.scala
app/controllers/property_or_land/RemovePropertyOrLandWithAddressInternationalController.scala
app/controllers/property_or_land/RemovePropertyOrLandWithAddressUKController.scala
app/controllers/property_or_land/RemovePropertyOrLandWithDescriptionController.scala
app/controllers/shares/RemoveShareCompanyNameAssetController.scala
app/controllers/shares/RemoveSharePortfolioAssetController.scala
app/models/UKAddress.scala
app/utils/AddAssetViewHelper.scala
app/viewmodels/addAnother/ShareAssetViewModel.scala
conf/app.routes
conf/messages.en
test/controllers/AddAssetsControllerSpec.scala
test/controllers/money/RemoveMoneyAssetControllerSpec.scala
test/controllers/property_or_land/RemovePropertyOrLandWithAddressInternationalControllerSpec.scala
test/controllers/property_or_land/RemovePropertyOrLandWithAddressUKControllerSpec.scala
test/controllers/property_or_land/RemovePropertyOrLandWithDescriptionControllerSpec.scala
test/controllers/shares/RemoveShareCompanyNameAssetControllerSpec.scala
test/controllers/shares/RemoveSharePortfolioAssetControllerSpec.scala
test/queries/RemoveAssetQuerySpec.scala
test/utils/AddABeneficiaryViewHelperSpec.scala
test/utils/AddAssetViewHelperSpec.scala
test/viewmodels/AssetViewModelSpec.scala

- Refactoring trait for RemoveIndexController to not have to
implement as much in the subclasses
- Adding in an inteface for Removing an asset

TRUS-1481 Implement remove asset

---

app/mapping/reads/PropertyOrLandAsset.scala
test/mapping/AssetMapperSpec.scala
test/mapping/PropertyOrLandMapperSpec.scala

fix-mappers

---

test/mapping/reads/AssetReadsSpec.scala

fix asset reads spec

---

app/forms/property_or_land/PropertyOrLandTotalValueFormProvider.scala

Update PropertyOrLandTotalValueFormProvider to validate as currency

TRUS-888-FIX

---

app/controllers/RemoveAssetController.scala
app/pages/DefaultRemoveAssetPage.scala
app/utils/AddAssetViewHelper.scala
app/viewmodels/addAnother/PropertyOrLandAssetViewModel.scala
conf/app.routes
conf/messages.en
test/controllers/DefaultRemoveAssetControllerSpec.scala
test/utils/AddAssetViewHelperSpec.scala
test/viewmodels/AssetViewModelSpec.scala

Allow user to remove any asset at index.

TRUS-1141 Render add row for property or land with no values

---

app/views/components/answer_row.scala.html

fix broken hidden links within check your answers

fix broken hidden links within check your answers

---

conf/messages.en

[TRUS-524] - Was holdover relief claimed on any assets put into the trust?

---

app/controllers/living_settlor/SettlorIndividualAnswerController.scala
app/utils/CheckYourAnswersHelper.scala
app/views/SettlorKindOfTrustView.scala.html
test/controllers/living_settlor/SettlorIndividualAnswerControllerSpec.scala
test/views/SettlorKindOfTrustViewSpec.scala

Amend settlorKindOfTrust view  for accessibility.
Update unit tests.

Add settlorKindOfTrust to CYA page

---

conf/messages.en

Correct label refs for Settlor What Kind of Trust page

Correct label refs for Settlor What Kind of Trust page

---

conf/messages.en

use correct apostrophe in message file for kind of trust hint text

[TRUS-948] - Add a Settlor Page - display hint text relevant to Trust Type selected

---

.g8/datePage/migrations/$className__snake$.sh
.g8/intPage/migrations/$className__snake$.sh
.g8/optionsPage/migrations/$className__snake$.sh
.g8/questionPage/migrations/$className__snake$.sh
.g8/stringPage/migrations/$className__snake$.sh
.g8/yesNoPage/migrations/$className__snake$.sh
app/controllers/living_settlor/SettlorIndividualAnswerController.scala
app/navigation/Navigator.scala
app/utils/CheckYourAnswersHelper.scala
test/controllers/living_settlor/SettlorIndividualAnswerControllerSpec.scala
test/navigation/NavigatorSpec.scala
test/navigation/navigators/TrustDetailsRoutes.scala

- After discussing with Rachel, when an answer is changed it takes the
user through the normal route and mandates they see the questions again

Change links in check answer now take the user to normal mode

---

conf/messages.en

Changed error message to say 'shares'

[TRUS-1481] - changed error message to say 'shares'

---

app/views/TaskListView.scala.html

[TRUS-1554] - Accessibility Automation - Element “p” not allowed as child of element “span” in this context

---

app/views/SettlorsBasedInTheUKView.scala.html
app/views/TrusteesBasedInTheUKView.scala.html

amend views to prevent repeat of H1

Accessibility fixes

---

app/assets/javascripts/trustsfrontend.js

Updated javaScript skiplink function

[TRUS-1293] - Accessibility - Jaws - Skip to main content reads out 'Get help with this page'

---

app/views/AddABeneficiaryView.scala.html
app/views/components/data_list.scala.html
conf/messages.en

Added missing message file entries.
Amended missing message entries for visually-hidden H2 tags.
Added aria-hidden attribute to H3 tags.

[TRUS-953] - Accessibility - Jaws & NVDA - Hidden heading announced between H1 & H3

---

conf/messages.en

Full stops added to hint text on inheritance act page and chargeable gains act page

Full stops added to hint text

---

app/pages/living_settlor/SettlorIndividualAddressUKYesNoPage.scala
app/pages/living_settlor/SettlorIndividualOrBusinessPage.scala
test/pages/living_settlor/SettlorIndividualAddressUKYesNoPageSpec.scala
test/pages/living_settlor/SettlorIndividualOrBusinessPageSpec.scala

Correct Living Settlor Clean-up Logic

[TRUS-1823] - Living Settlor Clean-up Logic

---

app/assets/stylesheets/trustsfrontend-app.scss
app/views/ClosedErrorView.scala.html
app/views/DoesNotMatchErrorView.scala.html
app/views/IVDownView.scala.html
app/views/StillProcessingErrorView.scala.html
conf/application.conf

Remove external links, amend heading size and spacing - IV Failure pages

Fix external links

---

app/assets/stylesheets/patterns/_add-to-a-list.scss

[TRUS-1929] - Check layout of content - Add a Beneficiary page

[TRUS-1929] - Check layout of content - Add a Beneficiary page

---

app/config/FrontendAppConfig.scala
app/navigation/Navigator.scala
app/views/InformationMaintainingThisTrustView.scala.html
conf/application.conf
test/navigation/navigators/registration/MatchingRoutes.scala
test/views/InformationMaintainingThisTrustViewSpec.scala

Correct variations feature toggle path.
Add new feature toggle paths for claim (to replace variations)
Add new feature toggle path for declaration email

[TRUS-2008] - Feature toggles

---

app/controllers/TrustStatusController.scala

TRUS-1986 Redirecting to information maintain when an agent is

---

app/connector/TrustClaim.scala
app/mapping/reads/Asset.scala
app/mapping/reads/Trustee.scala
app/viewmodels/addAnother/AssetViewModel.scala
app/viewmodels/addAnother/SettlorViewModel.scala

Resolve warnings - import scala.language.implicitConversions

Resolve warnings - import scala.language.implicitConversions

---

app/mapping/playback/DeceasedSettlorExtractor.scala
app/pages/register/settlors/deceased_settlor/SettlorsMetaData.scala
app/pages/register/settlors/deceased_settlor/SettlorsPassportIDCardPage.scala
app/pages/register/settlors/deceased_settlor/SettlorsSafeIdPage.scala
test/mapping/playback/DeceasedSettlorExtractorSpec.scala

[TRUS-2068] - Un-map Deceased Settlor

[TRUS-2068] - Un-map Deceased Settlor

---

app/mapping/playback/TrustBeneficiaryExtractor.scala
app/mapping/playback/UserAnswersExtractor.scala
app/pages/register/beneficiaries/trust/TrustBeneficiaryAddressPage.scala
app/pages/register/beneficiaries/trust/TrustBeneficiaryAddressUKYesNoPage.scala
app/pages/register/beneficiaries/trust/TrustBeneficiaryAddressYesNoPage.scala
app/pages/register/beneficiaries/trust/TrustBeneficiaryDiscretionYesNoPage.scala
app/pages/register/beneficiaries/trust/TrustBeneficiaryMetaData.scala
app/pages/register/beneficiaries/trust/TrustBeneficiaryNamePage.scala
app/pages/register/beneficiaries/trust/TrustBeneficiarySafeIdPage.scala
app/pages/register/beneficiaries/trust/TrustBeneficiaryShareOfIncomePage.scala
app/pages/register/beneficiaries/trust/TrustBeneficiaryUtrPage.scala
app/sections/TrustBeneficiaries.scala
test/mapping/playback/TrustBeneficiaryExtractorSpec.scala

[TRUS-2040] - Un-map Trust Beneficiary
Also added to UserAnswersExtractor (aware this will be placed into a BeneficiaryExtractor for ensuring there is at least one beneficiary entity added)

[TRUS-2040] - Un-map Trust Beneficiary

---

app/utils/CheckYourAnswersHelper.scala
app/utils/print/playback/sections/CharityBeneficiary.scala
conf/messages.en

Adding in UTR question for charity beneficiary

---

app/views/playback/PlaybackAnswersView.scala.html
conf/messages.en
test/views/playback/PlaybackAnswersViewSpec.scala

Ensuring the correct warnign and messages appear when rendering rows

TRUS-2252 Adding view spec and content for last declared view

---

app/mapping/playback/PlaybackExtractionErrors.scala
app/mapping/playback/beneficiaries/CompanyBeneficiaryExtractor.scala
app/sections/beneficiaries/CompanyBeneficiaries.scala
app/utils/print/playback/PlaybackAnswersHelper.scala
app/utils/print/playback/sections/AnswerRowConverter.scala
app/utils/print/playback/sections/CompanyBeneficiary.scala
conf/messages.en
test/mapping/playback/beneficiaries/BeneficiaryExtractorSpec.scala
test/mapping/playback/beneficiaries/CompanyBeneficiaryExtractorSpec.scala
test/utils/print/playback/BeneficiaryPlaybackHelperSpec.scala

TRUS-2252 Rendering company beneficiaries

---

app/sections/beneficiaries/OtherBeneficiaries.scala
app/utils/print/playback/PlaybackAnswersHelper.scala
app/utils/print/playback/sections/OtherBeneficiary.scala
conf/messages.en
test/utils/print/playback/BeneficiaryPrintPlaybackHelperSpec.scala

TRUS-2252 Rendering other beneficiary

---

app/utils/print/playback/sections/beneficiaries/TrustBeneficiary.scala
app/utils/print/playback/sections/protectors/BusinessProtector.scala
app/utils/print/playback/sections/protectors/IndividualProtector.scala
test/utils/print/playback/ProtectorPrintPlaybackHelperSpec.scala

Protector individual or business removed from playback print layout

Protector individual or business removed from playback print

---

app/utils/print/playback/sections/TrustDetails.scala

NonResidency type removed from playback print layout

NonResidency type removed from playback print

---

app/mapping/playback/TrustDetailsExtractor.scala
test/mapping/playback/TrustDetailsExtractorSpec.scala

TrustDetailsExtractor updated to handle administered in the United Kingdom

TrustDetailsExtractor updated to handle administered in GB

---

app/mapping/playback/beneficiaries/LargeBeneficiaryExtractor.scala
test/mapping/playback/beneficiaries/BeneficiaryExtractorSpec.scala
test/mapping/playback/beneficiaries/LargeBeneficiaryExtractorSpec.scala

Ranges added to numberOfBeneficiaries on playback printout to reflect possible inputs

Ranges added to numberOfBeneficiaries on playback

---

app/utils/CheckAnswersFormatters.scala
app/utils/print/playback/sections/AnswerRowConverter.scala
app/utils/print/playback/sections/beneficiaries/CharityBeneficiary.scala
app/utils/print/playback/sections/beneficiaries/ClassOfBeneficiary.scala
app/utils/print/playback/sections/beneficiaries/CompanyBeneficiary.scala
app/utils/print/playback/sections/beneficiaries/IndividualBeneficiary.scala
app/utils/print/playback/sections/beneficiaries/LargeBeneficiary.scala
app/utils/print/playback/sections/beneficiaries/OtherBeneficiary.scala
app/utils/print/playback/sections/beneficiaries/TrustBeneficiary.scala
test/utils/print/playback/BeneficiaryPrintPlaybackHelperSpec.scala

Percentage symbol added to relevant fields in playback printout

Percentage symbol added to relevant fields in playback

---

app/utils/print/playback/sections/trustees/lead_trustee/LeadTrusteeIndividual.scala
test/utils/print/playback/TrusteesPrintPlaybackHelperSpec.scala

Do you know Passport or ID card details question removed on playback printout for non-uk lead individual trustee

Do you know Passport or ID card details question removed

---

app/utils/print/playback/sections/beneficiaries/IndividualBeneficiary.scala
test/utils/print/playback/BeneficiaryPrintPlaybackHelperSpec.scala

NA changed to Not a Director or Employee for beneficiary type on playback

NA changed to Not a Director or Employee

---

conf/messages.en
test/views/playback/PlaybackAnswersViewSpec.scala

Wording of playback paragraphs updated

Wording of playback paragraphs updated

---

app/utils/print/playback/sections/trustees/TrusteeOrganisation.scala
app/utils/print/playback/sections/trustees/lead_trustee/LeadTrustee.scala
app/utils/print/playback/sections/trustees/lead_trustee/LeadTrusteeBusiness.scala
app/utils/print/playback/sections/trustees/lead_trustee/LeadTrusteeIndividual.scala
conf/messages.en
test/utils/print/playback/TrusteesPrintPlaybackHelperSpec.scala

Does [Name] live in the UK? changed to Is [Name] address in the UK? for Lead Trustee Companies on playback

Is Lead Trustee in the UK question amended

---

app/config/FrontendAppConfig.scala
app/controllers/register/TrustHaveAUTRController.scala
app/navigation/Navigator.scala
conf/application.conf
test/controllers/register/TrustHaveAUTRControllerSpec.scala
test/navigation/navigators/registration/MatchingRoutes.scala

- Pointing to use maintain-a-trust-frontend permentantely

Removing maintain feature

---

app/controllers/register/trustees/TrusteeUtrYesNoController.scala
app/navigation/Navigator.scala
app/views/register/trustees/TrusteeUtrYesNoView.scala.html
conf/messages.en
conf/register.routes
test/controllers/register/trustees/TrusteeUtrYesNoControllerSpec.scala
test/navigation/navigators/registration/TrusteeRoutes.scala
test/pages/register/trustees/TrusteeUtrYesNoPageSpec.scala
test/views/register/trustees/TrusteeUtrYesNoViewSpec.scala

Trustee UTR yes no page.
Controller, View unit tests.
Updated Navigation.

[TRUS-488] - Is this trustee a UK registered company?

---

app/pages/register/trustees/TrusteeIndividualOrBusinessPage.scala
app/utils/AddATrusteeViewHelper.scala
app/viewmodels/addAnother/TrusteeViewModel.scala
conf/messages.en
test/pages/register/trustees/TrusteeIndividualOrBusinessPageSpec.scala
test/utils/AddATrusteeViewHelperSpec.scala
test/viewmodels/TrusteeViewModelSpec.scala

Amend TrusteeViewModel to accept a name derived from FullName or String types

[TRUS-1581] - Logic for Add to Page and Registration Progress

---

app/models/registration/pages/ShareClass.scala
app/views/register/asset/shares/ShareClassView.scala.html
conf/messages.en
test/controllers/register/asset/shares/ShareClassControllerSpec.scala
test/forms/shares/ShareClassFormProviderSpec.scala
test/generators/ModelGenerators.scala
test/models/ShareClassSpec.scala
test/views/register/asset/shares/ShareClassViewSpec.scala

Fixing issue with agent international address and share class

---

app/views/components/input_text.scala.html
app/views/components/input_yes_no.scala.html
app/views/register/DeclarationView.scala.html
app/views/register/WhatIsTheUTRView.scala.html
app/views/register/agents/AgentInternalReferenceView.scala.html
app/views/register/agents/AgentNameView.scala.html
app/views/register/asset/money/AssetMoneyValueView.scala.html
app/views/register/asset/shares/ShareCompanyNameView.scala.html
app/views/register/asset/shares/SharePortfolioNameView.scala.html
app/views/register/beneficiaries/ClassBeneficiaryDescriptionView.scala.html
app/views/register/beneficiaries/IndividualBeneficiaryNameView.scala.html
app/views/register/settlors/deceased_settlor/SettlorsNameView.scala.html
app/views/register/settlors/living_settlor/SettlorIndividualNameView.scala.html
app/views/register/trust_details/TrustNameView.scala.html
app/views/register/trustees/individual/TrusteesNameView.scala.html
app/views/register/trustees/organisation/TrusteeBusinessNameView.scala.html
app/views/register/trustees/organisation/TrusteeUtrView.scala.html

aria required removed from views and components

TRUS-2691 : aria required removed from views and components

---

test/controllers/IndexValidation.scala

in terms of number of applications created.

Make the index validation tests a bit less heavy

---

app/views/register/asset/buisness/BusinessValueView.scala.html

Input mode added to BusinessValueView to rectify incorrect keyboard being shown on Android devices

Input mode added to BusinessValueView

---

app/views/components/input_date.scala.html
app/views/components/input_radio.scala.html
app/views/components/input_tele.scala.html
app/views/components/input_text.scala.html
app/views/components/input_textarea.scala.html
app/views/components/input_utr.scala.html
app/views/components/input_yes_no.scala.html

aria-describedby on the fieldset.
Hint text should appear before the error message.

[TRUS-2690] - correct error association as per pattern

---

app/utils/print/register/PrintUserAnswersHelper.scala

Add missing Partnership asset to prints
Re-order assets on prints

[TRUS-3358] - Add missing Partnership asset to prints

---

app/assets/stylesheets/colours/_palette.scss
app/assets/stylesheets/patterns/_notification.scss
app/assets/stylesheets/trustsfrontend-app.scss
app/config/FrontendAppConfig.scala
app/views/components/notification.scala.html
app/views/register/TaskListView.scala.html
app/views/register/agents/AgentOverviewView.scala.html
conf/application.conf
conf/messages.en
test/base/RegistrationSpecBase.scala
test/views/register/TaskListViewSpec.scala
test/views/register/agents/AgentOverviewViewSpec.scala

TRUS-4025 Add notification banner

---

app/controllers/actions/register/RegistrationIdentifierAction.scala
app/models/SubmissionDraftResponse.scala
app/pages/register/RegistrationProgress.scala
app/viewmodels/Link.scala
app/viewmodels/Task.scala
app/viewmodels/TaskDisplay.scala
app/views/components/TaskItem.scala.html
app/views/components/TaskList.scala.html
conf/messages.en
test/models/SubmissionDraftResponseSpec.scala
test/pages/register/RegistrationProgressSpec.scala
test/views/register/TaskListViewSpec.scala

Enable link:
- trust is taxable, new and there is a tax liability
Disable link:
- trust is taxable, new and there is no tax liability
- trust is taxable, new and start date is unknown
Hide link:
- trust is non-taxable
- trust is existing

TRUS-4430: Showing disabled tax liability link when no tax liability or start date unknown

---

app/views/components/ReturnToTop.scala.html

[CS] update returnToTop svg to aria-hidden

---

app/assets/javascripts/print.js
app/views/components/Button.scala.html
app/views/register/ConfirmationAnswerPageView.scala.html
app/views/register/SummaryAnswerPageView.scala.html

onClick events cannot work with the improved CSP that we've added, moved to eventListener based functionality in external js file to get around this. Example of working:

[DP][DDCE-2925] Allow print functionality through CSP

---

conf/messages
conf/messages.cy

Add schedule3aExemptYesNo.checkYourAnswersLabel to messages

[DDCE-3155] - Add schedule3aExemptYesNo.checkYourAnswersLabel

---

app/utils/AnswerRowUtils.scala
test/utils/AnswerRowUtilsSpec.scala

Screen shots showing examples have been attached to ticket.

DDCE-4612: Update Country Code matcher to only find exact matches
